export const eucaristicasData = [
    {
        id: "eucaristica-i",
        titulo: "Oração Eucarística I ou Cânon Romano",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Cânon Romano – Missal Romano pág. 523",
        texto: [
            "CP: Pai de misericórdia, a quem sobem nossos louvores, suplicantes, vos rogamos e pedimos por Jesus Cristo, vosso Filho e Senhor nosso, que aceiteis e abençoeis ✠ estes dons, estas oferendas, este sacrifício puro e santo, que oferecemos, antes de tudo, pela vossa Igreja santa e católica: concedei-lhe paz e proteção, unindo-a num só corpo e governando-a por toda a terra, em comunhão com o vosso servo o Papa N., o nosso Bispo N., e todos os que guardam a fé católica que receberam dos Apóstolos.",
            "AS: Abençoai nossa oferenda, ó Senhor!",
            {
                contexto: "memento dos vivos",
                texto: [
                    "1C: Lembrai-vos, ó Pai, dos vossos filhos e filhas N. N. e de todos os que circundam este altar, dos quais conheceis a fé e a dedicação ao vosso serviço. Por eles nós vos oferecemos e também eles vos oferecem este sacrifício de louvor por si e por todos os seus, e elevam a vós as suas preces, Deus eterno, vivo e verdadeiro, para alcançar o perdão de suas faltas, a segurança em suas vidas e a salvação que esperam.",
                    "AS: Lembrai-vos, ó Pai, de vossos filhos!"
                ]
            },
            {
                contexto: "Infra actionem",
                texto: [
                    "2C: Em comunhão com toda a Igreja, celebramos em primeiro lugar a memória da Mãe de nosso Deus e Senhor Jesus Cristo, a gloriosa sempre Virgem Maria, a de seu esposo São José, e também a dos Santos Apóstolos e Mártires: Pedro e Paulo, André, (Tiago e João, Tomé, Tiago e Filipe, Bartolomeu e Mateus, Simão e Tadeu, Lino, Cleto, Clemente, Sisto, Cornélio e Cipriano, Lourenço e Crisógono, João e Paulo, Cosme e Damião), e todos os vossos Santos. Por seus méritos e preces concedei-nos sem cessar a vossa proteção. (Por Cristo, nosso Senhor. Amém).",
                    "AS: Em comunhão com os vossos Santos vos louvamos!"
                ],
                variacoes: [
                    {
                        contexto: "Para os Domingos",
                        texto: [
                            "Em comunhão com toda a Igreja, celebramos o glorioso dia em que o Senhor venceu a morte e nos tornou participantes de sua vida imortal. Veneramos em primeiro lugar a memória da Mãe de nosso Deus e Senhor Jesus Cristo, a gloriosa sempre Virgem Maria,"
                        ]
                    },
                    {
                        contexto: "No Natal do Senhor e durante a Oitava",
                        texto: [
                            "Em comunhão com toda a Igreja, celebramos (a noite santíssima) o dia santíssimo, em que Maria, intacta em sua virgindade, deu à luz o Salvador do mundo. Veneramos em primeiro lugar a memória da mesma Mãe de nosso Deus e Senhor Jesus Cristo, a gloriosa sempre Virgem Maria,"
                        ]
                    },
                    {
                        contexto: "Na Epifania do Senhor",
                        texto: [
                            "Em comunhão com toda a Igreja, celebramos o dia santíssimo, em que vosso Filho unigênito, eterno convosco na glória, se manifestou visivelmente em nossa carne. Veneramos em primeiro lugar a memória da Mãe de nosso Deus e Senhor Jesus Cristo, a gloriosa sempre Virgem Maria,"
                        ]
                    },
                    {
                        contexto: "Da Vigília Pascal até o 2º domingo da Páscoa",
                        texto: [
                            "Em comunhão com toda a Igreja, celebramos (a noite santíssima) o dia santíssimo da Ressurreição de nosso Senhor Jesus Cristo segundo a carne. Veneramos em primeiro lugar a memória da Mãe de nosso Deus e Senhor Jesus Cristo, a gloriosa sempre Virgem Maria,"
                        ]
                    },
                    {
                        contexto: "Na Ascensão do Senhor",
                        texto: [
                            "Em comunhão com toda a Igreja, celebramos o dia santíssimo em que Nosso Senhor, vosso Filho unigênito, elevou à vossa direita na glória a nossa frágil natureza humana. Veneramos em primeiro lugar a memória da Mãe de nosso Deus e Senhor Jesus Cristo, a gloriosa sempre Virgem Maria,"
                        ]
                    },
                    {
                        contexto: "Em Pentecostes",
                        texto: [
                            "Em comunhão com toda a Igreja, celebramos o dia santíssimo de Pentecostes em que o Espírito Santo, em línguas de fogo, se manifestou aos Apóstolos. Veneramos em primeiro lugar a memória da mesma Mãe de nosso Deus e Senhor Jesus Cristo, a gloriosa sempre Virgem Maria,"
                        ]
                    }
                ]
            },
            "2C: Em comunhão com toda a Igreja, celebramos em primeiro lugar a memória da Mãe de nosso Deus e Senhor Jesus Cristo, a gloriosa sempre Virgem Maria, a de seu esposo São José, e também a dos Santos Apóstolos e Mártires: Pedro e Paulo, André, (Tiago e João, Tomé, Tiago e Filipe, Bartolomeu e Mateus, Simão e Tadeu, Lino, Cleto, Clemente, Sisto, Cornélio e Cipriano, Lourenço e Crisógeno, João e Paulo, Cosme e Damião), e todos os vossos Santos. Por seus méritos e preces concedei-nos sem cessar a vossa proteção. (Por Cristo, nosso Senhor. Amém).",
            "AS: Em comunhão com os vossos Santos vos louvamos!",
            "CP: Aceitai, ó Pai, com bondade, a oblação dos vossos servos e de toda a vossa família; dai-nos sempre a vossa paz, livrai-nos da condenação eterna e acolhei-nos entre os vossos eleitos. (Por Cristo, Senhor nosso. Amém)",
            "CC: Dignai-vos, ó Pai, aceitar, abençoar e santificar estas oferendas, recebei-as como sacrifício espiritual perfeito, a fim de que se tornem para nós o Corpo e ✠ o Sangue de vosso amado Filho, nosso Senhor Jesus Cristo.",
            "AS: Enviai o vosso Espírito Santo!",
            "Na véspera de sua paixão, ele tomou o pão em suas santas e veneráveis mãos, elevou os olhos ao céu, a vós, ó Pai, todo-poderoso, pronunciou a bênção de ação de graças, partiu o pão e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, ao fim da Ceia, ele tomou este precioso cálice em suas santas e veneráveis mãos, pronunciou novamente a bênção de ação de graças e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS, PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Celebrando, pois, a memória da bem-aventurada paixão do vosso Filho, da sua ressurreição dentre os mortos e gloriosa ascensão aos céus, nós, vossos servos, e também vosso povo santo, vos oferecemos, ó Pai, dentre os bens que nos destes, o sacrifício puro, santo e imaculado, Pão santo da vida eterna e Cálice da perpétua salvação. Recebei, ó Pai, com olhar benigno, esta oferta, como recebestes os dons do justo Abel, o sacrifício de nosso patriarca Abraão e a oblação pura e santa do sumo sacerdote Melquisedeque.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "Suplicantes, vos pedimos, ó Deus onipotente, que esta nossa oferenda seja levada à vossa presença, no altar do céu, pelas mãos do vosso santo Anjo, para que todos nós, participando deste altar, pela comunhão do santíssimo Corpo e Sangue do vosso Filho, sejamos repletos de todas as graças e bênçãos do céu. (Por Cristo, nosso Senhor. Amém)",
            "AS: O Espírito nos una num só corpo!",
            "3C: Lembrai-vos, ó Pai, dos vossos filhos e filhas N. N. que nos precederam com o sinal da fé e dormem o sono da paz. A eles, e a todos os que descansam no Cristo, concedei o repouso, a luz e a paz. (Por Cristo, nosso Senhor. Amém)",
            "AS: Concedei-lhes, ó Senhor, a luz eterna!",
            "4C: E a todos nós pecadores, que esperamos na vossa infinita misericórdia, concedei, não por nossos méritos, mas por vossa bondade, o convívio dos Apóstolos e Mártires: João Batista, Estevão, Matias e Barnabé, Inácio, Alexandre, Marcelino e Pedro, Felicidade e Perpétua, Águeda, Luzia, Inês, Cecília, Anastácia e todos os vossos Santos. Por Cristo, Senhor nosso.",
            "CP: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém."
        ]
    },
    {
        id: "eucaristica-ii",
        titulo: "Oração Eucarística II",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 536",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "CP: Na verdade, é digno e justo, é nosso dever e salvação dar-vos graças sempre e em todo o lugar, Senhor, Pai santo, por vosso amado Filho, Jesus Cristo. Ele é a vossa Palavra, pela qual tudo criastes. Ele é o nosso Salvador e Redentor, que se encarnou pelo Espírito Santo e nasceu da Virgem Maria. Ele, para cumprir a vossa vontade e adquirir para vós um povo santo, estendeu os braços na hora da sua paixão, a fim de vencer a morte e manifestar a ressurreição. Por isso, com os Anjos e todos os Santos, proclamamos vossa glória, cantando (dizendo) a uma só voz:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Na verdade, ó Pai, vós sois Santo, fonte de toda santidade.",
            "CC: Santificai, pois, estes dons, derramando sobre eles o vosso Espírito, a fim de que se tornem para nós o Corpo e ✠ o Sangue de nosso Senhor Jesus Cristo.",
            "AS: Enviai o Vosso Espírito Santo!",
            "Estando para ser entregue e abraçando livremente a paixão, Jesus tomou o pão, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, ele tomou o cálice em suas mãos e, dando graças novamente, o entregou a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS, PARA A REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Celebrando, pois, o memorial da morte e ressurreição do vosso Filho, nós vos oferecemos, ó Pai, o Pão da vida e o Cálice da salvação; e vos agradecemos porque nos tornastes dignos de estar aqui na vossa presença e vos servir.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "Suplicantes, vos pedimos que, participando do Corpo e Sangue de Cristo, sejamos reunidos pelo Espírito Santo num só corpo.",
            "AS: O Espírito nos una num só corpo!",
            {
                contexto: "memento dos vivos",
                texto: [
                    "1C: Lembrai-vos, ó Pai, da vossa Igreja que se faz presente pelo mundo inteiro; que ela cresça na caridade, em comunhão com o papa N., com o nosso bispo N., os bispos do mundo inteiro, os presbíteros, os diáconos e todos os ministros do vosso povo."
                ],
                variacoes: [
                    {
                        contexto: "aos Domingos",
                        texto: [
                            "Lembrai-vos, ó Pai, da vossa Igreja que se faz presente pelo mundo inteiro; e aqui convocada no dia em que Cristo venceu a morte e nos fez participantes de sua vida imortal;"
                        ]
                    }
                ]
            },
            "AS: Lembrai-vos, ó Pai, da vossa Igreja!",
            {
                contexto: "memento dos mortos",
                texto: [
                    "2C: Lembrai-vos do vosso filho (da vossa filha) N., que (hoje) chamastes deste mundo à vossa presença. Tendo sido sepultado (a) com Cristo em sua morte, no Batismo, participe igualmente da sua ressurreição.",
                    "2C: Lembrai-vos também, na vossa misericórdia, dos (outros) nossos irmãos e irmãs que adormeceram na esperança da ressurreição e de todos os que partiram desta vida; acolhei-os junto a vós na luz da vossa face."
                ]
            },
            "AS: Concedei-lhes, ó Senhor, a luz eterna!",
            "3C: Enfim, nós vos pedimos, tende piedade de todos nós e dai-nos participar da vida eterna, com a Virgem Maria, Mãe de Deus, São José, seu esposo, Os Apóstolos, (São N. Santo do dia ou padroeiro) e todos os Santos que neste mundo viveram na vossa amizade, a fim de vos louvarmos e glorificarmos por Jesus Cristo, vosso Filho.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda a honra e toda a glória, por todos os séculos dos séculos.",
            "AS: Amém!",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-iii",
        titulo: "Oração Eucarística III",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 545",
        texto: [
            "CP: Na verdade, vós sois Santo, ó Deus do universo, e tudo o que criastes proclama o vosso louvor, porque, por Jesus Cristo, vosso Filho e Senhor nosso, e pela força do Espírito Santo, dais vida e santidade a todas as coisas e não cessais de reunir para vós um povo que vos ofereça em toda parte, do nascer ao pôr do sol, um sacrifício perfeito.",
            "CC: Por isso, ó Pai, nós vos suplicamos: santificai pelo Espírito Santo as oferendas que vos apresentamos para serem consagradas a fim de que se tornem o Corpo ✠ e o Sangue de vosso Filho, nosso Senhor Jesus Cristo, que nos mandou celebrar estes mistérios.",
            "AS: Enviai o vosso Espírito Santo!",
            "Na noite em que ia ser entregue, Jesus tomou o pão, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, ao fim da Ceia, ele tomou o cálice em suas mãos, pronunciou a bênção de ação de graças, e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS, PARA A REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Celebrando agora, ó Pai, o memorial da paixão redentora do vosso Filho, da sua gloriosa ressurreição e ascensão ao céu, e enquanto esperamos sua nova vinda, nós vos oferecemos em ação de graças este sacrifício vivo e santo.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "Olhai com bondade a oblação da vossa Igreja e reconhecei nela o sacrifício que nos reconciliou convosco; concedei que, alimentando-nos com o Corpo e o Sangue do vosso Filho, repletos do Espírito Santo, nos tornemos em Cristo um só corpo e um só espírito.",
            "AS: O Espírito nos una num só corpo!",
            "1C: Que o mesmo Espírito faça de nós uma eterna oferenda para alcançarmos a herança com os vossos eleitos: a santíssima Virgem Maria, Mãe de Deus, São José, seu esposo, os vossos santos Apóstolos e gloriosos Mártires, N. (Santo do dia ou padroeiro) e todos os Santos, que não cessam de interceder por nós na vossa presença.",
            "AS: Fazei de nós um perfeita oferenda!",
            "2C: Nós vos suplicamos, Senhor, que este sacrifício da nossa reconciliação estenda a paz e a salvação ao mundo inteiro. Confirmai na fé e na caridade a vossa Igreja que caminha neste mundo com o vosso servo o Papa N., e o nosso Bispo N., com os bispos do mundo inteiro, os presbíteros e diáconos, os outros ministros e o povo por vós redimido. Atendei propício às preces desta família, que reunistes em vossa presença. Reconduzi a vós, Pai de misericórdia, todos os vossos filhos e filhas dispersos pelo mundo inteiro.",
            "AS: Lembrai-vos, ó Pai, da vossa Igreja!",
            "3C: Acolhei com bondade no vosso reino os nossos irmãos e irmãs que partiram desta vida e todos os que morreram na vossa amizade. Unidos a eles, esperamos também nós saciar-nos eternamente da vossa glória, por Cristo, Senhor nosso. Por ele dais ao mundo todo bem e toda graça",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém!",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-iv",
        titulo: "Oração Eucarística IV",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 554",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "CP: Na verdade, ó Pai, é nosso dever dar-vos graças, é nossa salvação dar-vos glória. Só vós sois o Deus vivo e verdadeiro que existis antes de todo o tempo e permaneceis para sempre, habitando em luz inacessível. Mas, porque sois o Deus de bondade e a fonte da vida, fizestes todas as coisas para cobrir de bênçãos as vossas criaturas e a muitos alegrar com a vossa luz. Eis, pois, diante de vós os inumeráveis coros dos Anjos que dia e noite vos servem e, contemplando a glória de vossa face, vos louvam sem cessar. Com eles também nós e, por nossa voz, tudo o que criastes celebramos o vosso Nome, e exultantes de alegria, cantamos (dizemos) a uma só voz:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Nós proclamamos vossa grandeza, Pai santo, a sabedoria e o amor com que fizestes todas as coisas. Criastes o ser humano à vossa imagem e lhe confiastes todo o universo para que, servindo somente a vós, seu Criador, cuidasse de toda criatura. E quando pela desobediência perdeu a vossa amizade, não o abandonastes ao poder da morte. A todos, porém, socorrestes com misericórdia, para que, ao procurar-vos, vos encontrassem. Muitas vezes oferecestes aliança à família humana e a instruístes pelos profetas na esperança da salvação.",
            "AS: A todos socorrestes com bondade!",
            "PR: E de tal modo, Pai santo, amastes o mundo que, chegada a plenitude dos tempos, nos enviastes vosso próprio Filho para ser o nosso Salvador. Encarnado pelo poder do Espírito Santo e nascido da Virgem Maria, Jesus viveu em tudo a condição humana, menos o pecado; anunciou aos pobres a salvação, aos oprimidos, a liberdade, aos tristes, a alegria. Para cumprir o vosso plano de amor, entregou-se à morte e, ressuscitando, destruiu a morte e renovou a vida.",
            "AS: Por amor nos enviastes vosso Filho!",
            "E, a fim de não mais vivermos para nós, mas para ele, que por nós morreu e ressuscitou, enviou de vós, ó Pai, como primeiro dom aos vossos fiéis, o Espírito Santo, que continua sua obra no mundo para levar à plenitude toda a santificação.",
            "CC: Por isso, nós vos pedimos, ó Pai, que o mesmo Espírito Santo santifique estas oferendas, a fim de que se tornem o Corpo ✠ e o Sangue de Jesus Cristo, vosso Filho e Senhor nosso, para celebrarmos este grande mistério que ele nos deixou em sinal da eterna aliança.",
            "AS: Enviai o vosso Espírito Santo!",
            "Quando, pois, chegou a hora em que por vós, ó Pai, ia ser glorificado, tendo amado os seus que estavam no mundo, amou-os até o fim. Enquanto ceavam, Jesus tomou o pão, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, ele tomou em suas mãos o cálice com o vinho , deu-vos graças novamente e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS, PRA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Celebrando, agora, ó Pai, o memorial da nossa redenção, anunciamos a morte de Cristo e sua descida entre os mortos, proclamamos a sua ressurreição e ascensão à vossa direita e, esperando a sua vinda gloriosa, nós vos oferecemos o seu Corpo e Sangue, sacrifício do vosso agrado e salvação do mundo inteiro.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "Olhai, com bondade, a oblação que destes à vossa Igreja e concedei aos que vamos participar do mesmo pão e do mesmo cálice que, reunidos pelo Espírito Santo num só corpo, nos tornemos em Cristo uma oferenda viva para o louvor da vossa glória.",
            "AS: O Espírito nos una num só corpo!",
            "1C: E agora, ó Pai, lembrai-vos de todos pelos quais vos oferecemos este sacrifício: o vosso servo o Papa N., o nosso Bispo N., os bispos do mundo inteiro, os presbíteros, os diáconos, e todos os ministros da vossa Igreja, os fiéis que, ao redor deste altar, se unem à nossa oferta, o povo que vos pertence e todos aqueles que vos procuram de coração sincero.",
            "AS: Lembrai-vos, ó Pai, da vossa Igreja!",
            "2C: Lembrai-vos também dos que morreram na paz do vosso Cristo e de todos os defuntos dos quais só vós conhecestes a fé.",
            "AS: Concedei-lhes, ó Senhor, a luz eterna!",
            "3C: E a todos nós, vossos Filhos e Filhas, concedei, ó Pai de bondade, alcançar a herança eterna, com a Virgem Maria, Mãe de Deus, São José, seu esposo, os Apóstolos e todos os Santos, no vosso reino, onde, com todas as criaturas, libertas da corrupção do pecado e da morte, vos glorificaremos por Cristo, Senhor nosso, por quem dais ao mundo todo bem e toda graça.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda a honra e toda a glória, por todos os séculos dos séculos.",
            "AS: Amém!",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-v",
        titulo: "Oração Eucarística V (do Congresso de Manaus)",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 564",
        observacao: "O prefácio não pode ser substituído por outro.",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "CP: É justo e nos faz todos ser mais santos, louvar a vós, ó Pai, no mundo inteiro, de dia e de noite, agradecendo com Cristo, vosso Filho, nosso irmão. É ele o sacerdote verdadeiro que sempre se oferece por nós todos, mandando que se faça a mesma coisa que fez naquela ceia derradeira. Por isso, aqui estamos bem unidos, louvando e agradecendo com alegria, juntando nossa voz à voz dos Anjos e dos Santos todos, para cantar (dizer):",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Ó Pai, vós que sempre quisestes ficar muito perto de nós, vivendo conosco no Cristo, falando conosco por ele, mandai o vosso Espírito Santo, a fim de que as nossas ofertas se mudem no Corpo ✠ e no Sangue de nosso Senhor Jesus Cristo.",
            "AS: Mandai vosso Espírito Santo!",
            "Na noite em que ia ser entregue, ceando com seus Apóstolos, Jesus tomou o pão em suas mãos, olhou para o céu e vos deu graças, partiu o pão e o entregou a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, tomou o cálice em suas mãos, deu-vos graças novamente e o entregou a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS, PARA A REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Tudo isto é mistério da fé!",
            "AS: Toda vez que comemos deste Pão, toda vez que bebemos deste Vinho, recordamos a paixão de Jesus Cristo e ficamos esperando sua vinda.",
            "CP: Recordando, ó Pai, neste momento, a paixão de Jesus, nosso Senhor, sua ressurreição e ascensão, nós queremos a vós oferecer este Pão que alimenta e que dá vida, este Vinho que nos salva e dá coragem.",
            "AS: Recebei, ó Senhor, a nossa oferta!",
            "CP: E quando recebermos Pão e Vinho, o Corpo e Sangue dele oferecidos, o Espírito nos una num só corpo, para sermos um só povo em seu amor.",
            "AS: O Espírito nos uma num só corpo!",
            "1C: Protegei vossa Igreja que caminha nas estradas do mundo rumo ao céu, cada dia renovando a esperança de chegar junto a vós, na vossa paz.",
            "AS: Caminhamos na estrada de Jesus!",
            "2C: Dai ao vosso servo, o Papa N., ser bem firme na fé, na caridade, e a N., que é Bispo desta Igreja, muita luz para guiar o vosso povo.",
            "AS: Lembrai-vos, ó Pai, da vossa Igreja!",
            "3C: Esperamos entrar na vida eterna com Maria, Mãe de Deus e da Igreja, os Apóstolos, e todos os que na vida souberam amar Cristo e seus irmãos.",
            "AS: Esperamos entrar na vida eterna!",
            "4C: Abri as portas da misericórdia aos que chamastes para a outra vida; acolhei-os juntos a vós, bem felizes no reino que para todos preparastes.",
            "AS: A todos dai a luz que não se apaga!",
            "CP: E a todos nós, aqui reunidos, que somos povo santo e pecador, dai-nos a graça de participar do vosso reino que também é nosso.",
            "CP ou CC: Por Cristo, com Cristo, em Cristo, a vós, Deus Pai todo poderoso, na unidade do Espírito Santo, toda honra e toda a glória, por todos os séculos dos séculos.",
            "AS: Amém!",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-d1",
        titulo: "Oração Eucarística (D1) - A Igreja A Caminho Da Unidade",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 614",
        observacao: "Para Diversas Circunstâncias I",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "CP: Na verdade, é digno e justo, é nosso dever e salvação dar-vos graças e cantar-vos um hino de glória e louvor, Senhor, Pai de infinita bondade. Pela palavra do Evangelho do vosso Filho reunistes uma só Igreja de todos os povos, línguas e nações. Por ela, vivificada pela força do vosso Espírito, não deixais de congregar na unidade todo o gênero humano. Manifestando a aliança do vosso amor, a Igreja irradia sem cessar a alegre esperança do vosso reino e brilha como sinal da vossa fidelidade que prometestes para sempre em Cristo Jesus, Senhor nosso. Por isso, unidos a todos os Anjos dos céus, nós vos celebramos na terra, cantando (dizendo) com a Igreja inteira a uma só voz:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Na verdade, vós sois Santo e digno de louvor, ó Deus, que amais os seres humanos e sempre os acompanhais no caminho da vida. Na verdade, é bendito o vosso Filho, presente no meio de nós, quando nos reunimos por seu amor. Como outrora aos discípulos de Emaús, ele nos revela as Escrituras e parte o Pão para nós.",
            "AS: Bendito o vosso Filho, presente entre nós!",
            "CC: Por isso, nós vos suplicamos, Pai de bondade: enviai e o vosso Espírito Santo para que santifique estes dons do pão e do vinho, e se tornem para nós o Corpo e ✠ o Sangue de nosso Senhor Jesus Cristo.",
            "AS: Enviai o vosso Espírito Santo!",
            "CP: Na véspera de sua paixão, na noite da última Ceia, Jesus tomou o pão, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, ele tomou o cálice em suas mãos, deu-vos graças novamente e o entregou a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Celebrando, pois, ó Pai santo, o memorial da Páscoa de Cristo, vosso Filho, nosso Salvador, anunciamos a obra do vosso amor; pela paixão e morte de cruz, vós o fizestes entrar na glória da ressurreição e o colocastes à vossa direita. Enquanto esperamos sua vinda gloriosa, nós vos oferecemos o Pão da vida e o Cálice da bênção.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "CC: Olhai com bondade a oferta da vossa Igreja; nela vos apresentamos o sacrifício pascal de Cristo, que nos foi entregue. E concedei que, pela força do Espírito do vosso amor, sejamos contados, agora e por toda a eternidade, entre os membros do vosso Filho, cujo Corpo e Sangue comungamos.",
            "AS: O Espírito nos una num só corpo!",
            "1C: Renovai, ó Pai, com a luz do Evangelho, a vossa Igreja (que está em N.). Fortalecei o vínculo da unidade entre os fiéis e os pastores do vosso povo, em comunhão com o nosso Papa N., o nosso Bispo N. e toda a ordem episcopal. Assim, neste mundo dilacerado por discórdias, o vosso povo brilhe como sinal profético de unidade e concórdia.",
            "AS: Confirmai na unidade a vossa Igreja!",
            "2C: Lembrai-vos dos nossos irmãos e irmãs (N. e N.), que adormeceram na paz do vosso Cristo, e de todos os falecidos, cuja fé só vós conhecestes: acolhei-os na luz da vossa face e, na ressurreição, concedei-lhes a plenitude da vida.",
            "AS: Concedei-lhes, ó Senhor, a luz eterna!",
            "3C: Concedei também a nós, no fim da nossa peregrinação terrestre, chegarmos todos à morada eterna, onde viveremos para sempre convosco e, com a Bem-aventurada Virgem Maria, Mãe de Deus, os Apóstolos e Mártires, (São N.: Santo do dia ou padroeiro) e todos os Santos, vos louvaremos e glorificaremos, por Jesus Cristo, vosso Filho.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-d2",
        titulo: "Oração Eucarística (D2) - Deus Conduz Sua Igreja No Caminho Da Salvação",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 620",
        observacao: "Para Diversas Circunstâncias II",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "CP: Na verdade, é digno e justo, é nosso dever e salvação dar-vos graças, sempre e em todo lugar, Senhor, Pai santo, criador do mundo e fonte de toda vida. Nunca abandonais a obra da vossa sabedoria, mas, em vossa providência, continuais agindo no meio de nós. Com braço estendido e mão forte, guiastes o vosso povo de Israel pelo deserto. Agora, com a força do Espírito Santo, acompanhais sempre a vossa Igreja, peregrina neste mundo, e a conduzis pelos caminhos da história até à felicidade perfeita em vosso reino por Jesus Cristo, Senhor nosso. Por isso, também nós, com os Anjos e Santos, proclamamos o hino de vossa glória, cantando (dizendo) sem cessar:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Na verdade, vós sois Santo e digno de louvor, ó Deus, que amais os seres humanos e sempre os acompanhais no caminho da vida. Na verdade, é bendito o vosso Filho, presente no meio de nós, quando nos reunimos por seu amor. Como outrora aos discípulos de Emaús, ele nos revela as Escrituras e parte o Pão para nós.",
            "AS: Bendito o vosso Filho, presente entre nós!",
            "CC: Por isso, nós vos suplicamos, Pai de bondade: enviai e o vosso Espírito Santo para que santifique estes dons do pão e do vinho, e se tornem para nós o Corpo e ✠ o Sangue de nosso Senhor Jesus Cristo.",
            "AS: Enviai o vosso Espírito Santo!",
            "Na véspera de sua paixão, na noite da última Ceia, Jesus tomou o pão, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, ele tomou o cálice em suas mãos, deu-vos graças novamente e o entregou a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Celebrando, pois, ó Pai santo, o memorial da Páscoa de Cristo, vosso Filho, nosso Salvador, anunciamos a obra do vosso amor; pela paixão e morte de cruz, vós o fizestes entrar na glória da ressurreição e o colocastes à vossa direita. Enquanto esperamos sua vinda gloriosa, nós vos oferecemos o Pão da vida e o Cálice da bênção.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "CC: Olhai com bondade a oferta da vossa Igreja; nela vos apresentamos o sacrifício pascal de Cristo, que nos foi entregue. E concedei que, pela força do Espírito do vosso amor, sejamos contados, agora e por toda a eternidade, entre os membros do vosso Filho, cujo Corpo e Sangue comungamos.",
            "AS: O Espírito nos una num só corpo!",
            "1C: Ó Pai, confirmai na unidade os convidados a participar da vossa mesa, para que, seguindo na fé e na esperança pelos vossos caminhos, possamos irradiar no mundo alegria e confiança em comunhão com o nosso Papa N., o nosso Bispo N., todos os bispos, presbíteros, diáconos e todo o vosso povo.",
            "AS: Confirmai na unidade a vossa Igreja!",
            "2C: Lembrai-vos dos nossos irmãos e irmãs (N. e N.), que adormeceram na paz do vosso Cristo, e de todos os falecidos, cuja fé só vós conhecestes: acolhei-os na luz da vossa face e, na ressurreição, concedei-lhes a plenitude da vida.",
            "AS: Concedei-lhes, ó Senhor, a luz eterna!",
            "3C: Concedei também a nós, no fim da nossa peregrinação terrestre, chegarmos todos à morada eterna, onde viveremos para sempre convosco e, com a Bem-aventurada Virgem Maria, Mãe de Deus, os Apóstolos e Mártires, (São N.: Santo do dia ou padroeiro) e todos os Santos, vos louvaremos e glorificaremos, por Jesus Cristo, vosso Filho.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-d3",
        titulo: "Oração Eucarística (D3) - Jesus, Caminho para o Pai",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 626",
        observacao: "Para Diversas Circunstâncias III",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "CP: Na verdade, é digno e justo, é nosso dever e salvação dar-vos graças, sempre e em todo lugar, Pai santo, Senhor do céu e da terra, por Cristo, Senhor nosso. De fato, pelo vosso Verbo criastes o universo e tudo governais com equidade. Vós nos destes vosso Filho, feito carne, como mediador; ele nos dirigiu a vossa palavra e nos chamou a seguir os seus passos. Ele é o caminho que nos conduz até vós, a verdade que nos liberta, a vida que nos enche de alegria. Por vosso Filho, reunis em uma só família os homens e as mulheres, criados para a glória do vosso nome, redimidos pelo sangue de sua cruz e marcados com o selo do vosso Espírito. Por isso, agora e para sempre, unidos a todos os Anjos, proclamamos a vossa glória, cantando (dizendo) com alegria:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Na verdade, vós sois Santo e digno de louvor, ó Deus, que amais os seres humanos e sempre os acompanhais no caminho da vida. Na verdade, é bendito o vosso Filho, presente no meio de nós, quando nos reunimos por seu amor. Como outrora aos discípulos de Emaús, ele nos revela as Escrituras e parte o Pão para nós.",
            "AS: Bendito o vosso Filho, presente entre nós!",
            "CC: Por isso, nós vos suplicamos, Pai de bondade: enviai e o vosso Espírito Santo para que santifique estes dons do pão e do vinho, e se tornem para nós o Corpo e ✠ o Sangue de nosso Senhor Jesus Cristo.",
            "AS: Enviai o vosso Espírito Santo!",
            "Na véspera de sua paixão, na noite da última Ceia, Jesus tomou o pão, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, ele tomou o cálice em suas mãos, deu-vos graças novamente e o entregou a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Celebrando, pois, ó Pai santo, o memorial da Páscoa de Cristo, vosso Filho, nosso Salvador, anunciamos a obra do vosso amor; pela paixão e morte de cruz, vós o fizestes entrar na glória da ressurreição e o colocastes à vossa direita. Enquanto esperamos sua vinda gloriosa, nós vos oferecemos o Pão da vida e o Cálice da bênção.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "CC: Olhai com bondade a oferta da vossa Igreja; nela vos apresentamos o sacrifício pascal de Cristo, que nos foi entregue. E concedei que, pela força do Espírito do vosso amor, sejamos contados, agora e por toda a eternidade, entre os membros do vosso Filho, cujo Corpo e Sangue comungamos.",
            "AS: O Espírito nos una num só corpo!",
            "1C: Pela participação neste mistério, ó Pai todo-poderoso, vivificai-nos no Espírito, tornai-nos semelhantes à imagem do vosso Filho e confirmai-nos no vínculo da comunhão com o nosso Papa N., o nosso Bispo N., os outros bispos, os presbíteros e diáconos e todo o vosso povo.",
            "AS: Confirmai na unidade a vossa Igreja!",
            "2C: Fazei que todos os fiéis da Igreja, discernindo os sinais dos tempos à luz da fé, empenhem-se coerentemente no serviço do Evangelho. Tornai-nos atentos às necessidades de todas as pessoas para que, participando de suas dores e angústias, de suas alegrias e esperanças, fielmente lhes anunciemos a salvação e, com eles, sigamos no caminho do vosso reino.",
            "AS: Ajudai-nos a criar um mundo novo!",
            "3C: Lembrai-vos dos nossos irmãos e irmãs (N. e N.), que adormeceram na paz do vosso Cristo, e de todos os falecidos, cuja fé só vós conhecestes: acolhei-os na luz da vossa face e, na ressurreição, concedei-lhes a plenitude da vida.",
            "AS: Concedei-lhes, ó Senhor, a luz eterna!",
            "4C: Concedei também a nós, no fim da nossa peregrinação terrestre, chegarmos todos à morada eterna, onde viveremos para sempre convosco e, com a Bem-aventurada Virgem Maria, Mãe de Deus, os Apóstolos e Mártires, (São N.: Santo do dia ou padroeiro) e todos os Santos, vos louvaremos e glorificaremos, por Jesus Cristo, vosso Filho.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-d4",
        titulo: "Oração Eucarística (D4) - Jesus que passa fazendo o bem",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 632",
        observacao: "Para Diversas Circunstâncias IV",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "CP: Na verdade, é digno e justo, é nosso dever e salvação dar-vos graças, sempre e em todo lugar, Pai das misericórdias e Deus fiel, pois nos destes vosso Filho Jesus Cristo, como Senhor e Redentor. Ele sempre se mostrou cheio de misericórdia para com os pequenos e os pobres, os doentes e os pecadores, e se fez próximo dos aflitos e oprimidos. Por sua palavra e ação anunciou ao mundo que sois Pai e cuidais de todos os vossos filhos e filhas. Por isso, com todos os Anjos e Santos, nós vos louvamos e bendizemos, e proclamamos o hino de vossa glória, cantando (dizendo) sem cessar:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Na verdade, vós sois Santo e digno de louvor, ó Deus, que amais os seres humanos e sempre os acompanhais no caminho da vida. Na verdade, é bendito o vosso Filho, presente no meio de nós, quando nos reunimos por seu amor. Como outrora aos discípulos de Emaús, ele nos revela as Escrituras e parte o Pão para nós.",
            "AS: Bendito o vosso Filho, presente entre nós!",
            "CC: Por isso, nós vos suplicamos, Pai de bondade: enviai e o vosso Espírito Santo para que santifique estes dons do pão e do vinho, e se tornem para nós o Corpo e ✠ o Sangue de nosso Senhor Jesus Cristo.",
            "AS: Enviai o vosso Espírito Santo!",
            "Na véspera de sua paixão, na noite da última Ceia, Jesus tomou o pão, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, ele tomou o cálice em suas mãos, deu-vos graças novamente e o entregou a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Celebrando, pois, ó Pai santo, o memorial da Páscoa de Cristo, vosso Filho, nosso Salvador, anunciamos a obra do vosso amor; pela paixão e morte de cruz, vós o fizestes entrar na glória da ressurreição e o colocastes à vossa direita. Enquanto esperamos sua vinda gloriosa, nós vos oferecemos o Pão da vida e o Cálice da bênção.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "CC: Olhai com bondade a oferta da vossa Igreja; nela vos apresentamos o sacrifício pascal de Cristo, que nos foi entregue. E concedei que, pela força do Espírito do vosso amor, sejamos contados, agora e por toda a eternidade, entre os membros do vosso Filho, cujo Corpo e Sangue comungamos.",
            "AS: O Espírito nos una num só corpo!",
            "1C: Dignai-vos, Senhor, conduzir a vossa Igreja à perfeição na fé e no amor, em comunhão com o nosso Papa N. e o nosso Bispo N., com todos os bispos, presbíteros, diáconos e todo o povo que adquiristes para vós.",
            "AS: Confirmai na unidade a vossa Igreja!",
            "2C: Abri os nossos olhos para perceber as necessidades dos irmãos e irmãs; inspirai-nos palavras e ações para confortar os cansados e oprimidos; fazei que os sirvamos de coração sincero, seguindo o exemplo e o mandamento de Cristo. Vossa Igreja seja testemunha viva da verdade e da liberdade, da justiça e da paz, para que toda a humanidade se reanime com uma nova esperança.",
            "AS: Ajudai-nos a criar um mundo novo!",
            "3C: Lembrai-vos dos nossos irmãos e irmãs (N. e N.), que adormeceram na paz do vosso Cristo, e de todos os falecidos, cuja fé só vós conhecestes: acolhei-os na luz da vossa face e, na ressurreição, concedei-lhes a plenitude da vida.",
            "AS: Concedei-lhes, ó Senhor, a luz eterna!",
            "4C: Concedei também a nós, no fim da nossa peregrinação terrestre, chegarmos todos à morada eterna, onde viveremos para sempre convosco e, com a Bem-aventurada Virgem Maria, Mãe de Deus, os Apóstolos e Mártires, (São N.: Santo do dia ou padroeiro) e todos os Santos, vos louvaremos e glorificaremos, por Jesus Cristo, vosso Filho.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-r1",
        titulo: "Oração Eucarística (R1) - sobre a Reconciliação I",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 602",
        observacao: "Sobre a Reconciliação I",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "Na verdade, é digno e justo dar-vos graças sempre, Senhor, Pai santo, Deus eterno e todo-poderoso. Constantemente nos chamais a uma vida mais plena e, porque sois rico em misericórdia, sempre ofereceis o perdão e convidais os pecadores a confiar somente na vossa bondade.",
            "E a nós, que tantas vezes quebramos a vossa aliança, nunca nos rejeitastes, mas, por Jesus, vosso Filho, nosso Redentor, unistes convosco a família humana com um vínculo novo de caridade, tão estreito e forte, que nada poderá romper.",
            "Também hoje, ofereceis tempo de graça e reconciliação ao vosso povo e um novo alento para que, em Cristo, se converta a vós, enquanto, sempre mais dócil ao Espírito Santo, se coloca ao serviço de todos.",
            "Por isso, cheios de admiração, exaltamos a força do vosso amor e, proclamando nossa alegria pela salvação, nos unimos às multidões dos céus, cantando (dizendo) sem cessar:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Na verdade, ó Pai, vós sois Santo e, desde a origem do mundo, tudo fazeis para sermos santos como vós sois Santo.",
            "CC: Olhai as oferendas do vosso povo e derramai sobre elas a força do vosso Espírito, para que se tornem o Corpo ✠ e o Sangue do vosso amado Filho, Jesus Cristo, no qual também nós somos vossos filhos.",
            "AS: Enviai o vosso Espírito Santo!",
            "Quando outrora estávamos perdidos e incapazes de vos encontrar, vós nos amastes com imenso amor, pois vosso Filho, o único Justo, entregou-se à morte, não rejeitando ser pregado no lenho da cruz. Antes, porém, de seus braços abertos traçarem entre o céu e a terra o sinal permanente da vossa aliança, Jesus quis celebrar a Páscoa com seus discípulos. Ceando com eles,tomou o pão, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, Jesus, sabendo que ia reconciliar em si todas as coisas pelo sangue a ser derramado na cruz, tomou o cálice repleto do fruto da videira, deu-vos graças novamente e o entregou a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Fazendo, pois, memória de vosso Filho, Jesus Cristo, nossa Páscoa e certeza da paz definitiva, celebramos sua morte e ressurreição e, aguardando o dia feliz de sua vinda gloriosa, nós vos oferecemos, Deus fiel e misericordioso, a vítima que nos reconcilia convosco.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "CC: Olhai, com amor, Pai misericordioso, aqueles que unis a vós pelo sacrifício do vosso Filho, e concedei que, pela força do Espírito Santo, os que participam do único pão e do mesmo cálice sejam congregados em Cristo num só corpo, no qual todas as divisões sejam superadas.",
            "AS: O Espírito nos una num só corpo!",
            "1C: Conservai-nos sempre em comunhão de fé e amor unidos ao Papa N. e ao nosso Bispo N.. Ajudai-nos a esperar juntos a vinda do vosso reino, até o dia em que, diante de vós, formos santos entre os Santos na morada celeste, ao lado da Virgem Maria, Mãe de Deus, dos Apóstolos e todos os Santos e com nossos irmãos e irmãs já falecidos que confiamos à vossa misericórdia. Enfim, libertos das feridas do pecado e plenamente transformados em novas criaturas, felizes cantaremos a ação de graças do vosso Cristo que vive para sempre.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-r2",
        titulo: "Oração Eucarística (R2) - sobre a Reconciliação II",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 608",
        observacao: "Sobre a Reconciliação II",
        texto: [
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "Na verdade, é digno e justo dar-vos graças e cantar vossos louvores, Deus Pai todo-poderoso, por tudo que operais neste mundo, por Cristo, nosso Senhor.",
            "No meio da humanidade dividida por inimizades e discórdias, sabemos por experiência que vós levais as pessoas a se converter e buscar a reconciliação.",
            "Pelo vosso Espírito Santo moveis os corações, de modo que os inimigos voltem à amizade, os adversários se deem as mãos e os povos procurem reencontrar a paz.",
            "É também obra do vosso poder, ó Pai, quando o ódio é vencido pelo amor, a vingança dá lugar ao perdão e a discórdia se converte em mútua afeição.",
            "Por isso, com os coros celestes, nós vos damos graças sem cessar e proclamamos aqui na terra a vossa glória, cantando (dizendo) a uma só voz:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Pai onipotente, louvado sois por vosso Filho Jesus Cristo, que veio em vosso nome. Ele é a Palavra de salvação para a humanidade, a mão que estendeis aos pecadores e o caminho pelo qual nos é concedida a vossa paz. Quando vos abandonamos por nossos pecados, vós nos reconduzistes à reconciliação por vosso Filho, que por nós entregastes à morte, para que voltássemos a vós e nos amássemos uns aos outros.",
            "CC: E agora, celebrando a reconciliação que Cristo nos trouxe, vos pedimos: santificai estas oferendas pela efusão do vosso Espírito, a fim de que se tornem o Corpo e ✠ o Sangue do vosso Filho que nos mandou celebrar estes mistérios.",
            "AS: Enviai o vosso Espírito Santo!",
            "Antes de dar a vida para nos libertar, estando à mesa, Jesus tomou o pão em suas mãos, pronunciou a bênção de ação de graças, partiu e o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, naquela noite, ele tomou o cálice da bênção em suas mãos e, proclamando a vossa misericórdia, o deu a seus discípulos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Ou:",
            "Mistério da fé e do amor!",
            "AS: Todas as vezes que comemos deste pão e bebemos deste cálice, anunciamos, Senhor, a vossa morte, enquanto esperamos a vossa vinda!",
            "Ou:",
            "Mistério da fé para a salvação do mundo!",
            "AS: Salvador do mundo, salvai-nos, vós que nos libertastes pela cruz e ressurreição.",
            "CC: Fazendo, pois, memória da morte e ressurreição do vosso Filho que nos deixou esta prova de amor, nós vos oferecemos aquilo que nos destes: o sacrifício da perfeita reconciliação.",
            "AS: Aceitai, ó Senhor, a nossa oferta!",
            "CC: Pai santo, neste banquete salvífico, suplicantes, vos pedimos: aceitai-nos também com vosso Filho e dai-nos o seu Espírito para que nos liberte de tudo que nos separa uns dos outros.",
            "AS: O Espírito nos una num só corpo!",
            "1C: Ele faça da vossa Igreja sinal de unidade do gênero humano e instrumento da vossa paz, e nos conserve em comunhão com o Papa N., o nosso Bispo N., os Bispos do mundo inteiro e todo o vosso povo.",
            "AS: Lembrai-vos, ó Pai, da vossa Igreja!",
            "2C: Ó Pai, que agora nos reunistes, à mesa do vosso Filho, congregai-nos também na Ceia da comunhão eterna nos novos céus e nova terra, onde brilha a plenitude da vossa paz, junto com a gloriosa Virgem Maria, Mãe de Deus, os Apóstolos e todos os Santos, os nossos irmãos e as pessoas de todos os povos e línguas que morreram na vossa amizade, em Cristo Jesus, Senhor nosso.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-c1",
        titulo: "Oração Eucarística (C1) - Para Missas com Crianças I",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 639",
        observacao: "O uso desta Oração Eucarística é restrito às Missas que se celebram só com crianças, isto é, as que ainda não entraram na adolescência, ou àquelas Missas nas quais a maior parte dos participantes é criança. O prefácio dessa Oração Eucarística, por sua estrutura e índole peculiar, não pode ser substituído por outros prefácios.",
        texto: [
            "[Rúbrica Litúrgica]\nO uso desta Oração Eucarística é restrito às Missas que se celebram só com crianças, isto é, as que ainda não entraram na adolescência, ou àquelas Missas nas quais a maior parte dos participantes é criança.\nO prefácio dessa Oração Eucarística, por sua estrutura e índole peculiar, não pode ser substituído por outros prefácios.",
            "",
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "Senhor, Pai de bondade, nos reunistes diante de vós para vos celebrar e proclamar vossos louvores com o coração em festa.",
            "Nós vos louvamos por todas as coisas bonitas que existem no mundo e pela alegria que dais a todos nós. Nós vos louvamos pela luz do dia e por vossa Palavra que nos ilumina. Nós vos louvamos também pela terra, pelas pessoas que nela habitam e pela vida que de vós recebemos.",
            "AS: Glória a vós, Senhor, que tanto nos amais!",
            "Sim, ó Pai, sois muito bom: vós nos amais e fazeis por nós coisas maravilhosas, sempre pensais em todas as pessoas e nunca desistis de estar perto delas. Enviastes vosso Filho querido para nos salvar. Ele curou os doentes, perdoou os pecadores, mostrou a todos o vosso amor, acolheu e abençoou as crianças.",
            "AS: Glória a vós, Senhor, que tanto nos amais!",
            "Pai de bondade, nós não estamos sozinhos para celebrar vossos louvores, pois em toda a terra o vosso povo vos glorifica. Por isso, rezamos com a Igreja inteira, com o Papa N. e o nosso Bispo N.. No céu também vos louvam sem cessar Maria, a Mãe de Jesus, os Apóstolos e todos os Santos. Unidos a eles e aos Anjos nós vos adoramos, cantando (dizendo) a uma só voz:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Pai santo, para vos agradecer, trouxemos este pão e este vinho;",
            "CC: pela ação do Espírito Santo fazei que eles se tornem o Corpo ✠ e o Sangue de Jesus Cristo, vosso Filho muito amado. Assim, ó Pai, possamos oferecer o mesmo dom que vós nos dais.",
            "AS: Enviai o vosso Espírito Santo!",
            "Jesus, na noite antes de sua morte na cruz, pôs-se à mesa com seus apóstolos, tomou o pão em suas mãos, e, rezando, deu graças; partiu o pão e o deu a seus amigos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, Jesus tomou em suas mãos o cálice com vinho, rezou, de novo, em ação de graças e o deu a seus amigos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "CC: Nesta Eucaristia, nós fazemos com amor o que Jesus mandou e, anunciando a sua morte e ressurreição, vos oferecemos o Pão da vida e o Cálice da salvação. Pai querido, é Jesus que nos conduz a vós; por isso, vos pedimos, recebei-nos com Ele.",
            "AS: Com Jesus, recebei a nossa vida!",
            "Pai, que tanto nos amais, deixai-nos aproximar desta mesa e enviai sobre nós o Espírito Santo para que, alimentando-nos com o Corpo e Sangue do vosso Filho, sejamos um só coração e uma só alma.",
            "AS: Fazei de nós um só corpo e um só espírito!",
            "1C: Senhor, que sempre vos lembrais de todos, nós vos pedimos por aqueles que amamos: o Papa N. e o nosso Bispo N., nossos pais, irmãos, amigos e os que cuidam de nós. Lembrai-vos também dos que sofrem em suas dores e andam tristes, e dos que morreram na vossa paz. Ó Pai, olhai com carinho o povo cristão e as pessoas do mundo inteiro. Diante de tudo o que fazeis em nosso favor por meio de Jesus Cristo, vosso Filho, nós vos bendizemos e louvamos.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-c2",
        titulo: "Oração Eucarística (C2) - Para Missas com Crianças II",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 645",
        observacao: "O uso desta Oração Eucarística é restrito às Missas que se celebram só com crianças, isto é, as que ainda não entraram na adolescência, ou àquelas Missas nas quais a maior parte dos participantes é criança. O prefácio dessa Oração Eucarística, por sua estrutura e índole peculiar, não pode ser substituído por outros prefácios.",
        texto: [
            "[Rúbrica Litúrgica]\nO uso desta Oração Eucarística é restrito às Missas que se celebram só com crianças, isto é, as que ainda não entraram na adolescência, ou àquelas Missas nas quais a maior parte dos participantes é criança.\nO prefácio dessa Oração Eucarística, por sua estrutura e índole peculiar, não pode ser substituído por outros prefácios.",
            "",
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "Ó Pai querido, que tanto nos amais, como é grande a nossa alegria em vos agradecer e com Jesus, na vossa Igreja, cantar vosso louvor.",
            "Vós nos amastes tanto que criastes para nós este mundo imenso e maravilhoso. Vós nos amais tanto que nos dais vosso Filho Jesus para nos guiar até vós. Vós nos amais tanto que nos reunis em vosso Filho Jesus e, pelo Espírito Santo, nos tornais filhos e filhas da mesma família.",
            "Por este amor tão grande nós vos agradecemos e com os Anjos e os Santos, que vos adoram, cantamos (dizemos) a uma só voz:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Sim, bendito seja Jesus que vós nos enviastes, amigo das crianças e dos pobres. Ele nos ensina a vos amar, ó Pai querido, e amar-nos uns aos outros.",
            "AS: Glória a vós, Senhor, que tanto nos amais!",
            "Jesus veio tirar do coração o pecado, a maldade e o ódio que impedem a amizade e não nos deixam ser felizes. Ele prometeu que o Espírito Santo ficaria sempre conosco para vivermos bem unidos a vós como filhos e filhas.",
            "AS: Glória a vós, Senhor, que tanto nos amais!",
            "CC: Ó Deus, nosso Pai, enviai vosso Espírito Santo para que estes dons do pão e do vinho se tornem o Corpo ✠ e o Sangue de nosso Senhor Jesus Cristo.",
            "AS: Enviai o vosso Espírito Santo!",
            "Jesus, na noite antes de sua morte na cruz, nos mostrou como é grande vosso amor. Quando ele estava à mesa com os apóstolos, tomou o pão em suas mãos e rezou, louvando e agradecendo. Depois partiu o pão e o deu a seus amigos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Jesus tomou em suas mãos o cálice com vinho, rezou, de novo, em ação de graças e o deu a seus amigos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "CC: Por isso, Pai querido, celebramos a memória da morte e ressurreição de Jesus, Salvador do mundo. Ele mesmo se colocou em nossas mãos para ser este dom de reconciliação e de paz, nosso sacrifício que agora vos oferecemos e pelo qual somos atraídos para vós.",
            "AS: Com Jesus, recebei a nossa vida!",
            "1C: Escutai-nos, Senhor nosso Deus, e dai o Espírito do vosso amor aos que participam desta Ceia, para que fiquem sempre mais unidos na vossa Igreja, com o nosso Papa N., o nosso Bispo N., os outros bispos e todos aqueles que servem o vosso povo.",
            "AS: Fazei de nós um só corpo e um só espírito!",
            "2C: Não vos esqueçais daqueles que amamos: nossos pais, parentes, amigos e os que cuidam de nós; e também daqueles que ainda não amamos bastante. Lembrai-vos dos que em paz partiram desta vida (N. N.); acolhei-os com amor na alegria da vossa casa.",
            "AS: Fazei de nós um só corpo e um só espírito!",
            "3C: Um dia, enfim, ó Pai, reuni a todos nós em vosso reino, com a Virgem Maria, Mãe de Deus e nossa Mãe, para celebrar a festa que no céu nunca se acaba, onde todos os amigos de Jesus cantam sem cessar o vosso louvor.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    },
    {
        id: "eucaristica-c3",
        titulo: "Oração Eucarística (C3) - Para Missas com Crianças III",
        subtitulo: "Texto Oficial da Terceira Edição Típica do Missal Romano",
        edicao: "Nova Edição (2023) – Missal Romano pág. 651",
        observacao: "O uso desta Oração Eucarística é restrito às Missas que se celebram só com crianças, isto é, as que ainda não entraram na adolescência, ou àquelas Missas nas quais a maior parte dos participantes é criança. O prefácio dessa Oração Eucarística, por sua estrutura e índole peculiar, não pode ser substituído por outros prefácios.",
        texto: [
            "[Rúbrica Litúrgica]\nO uso desta Oração Eucarística é restrito às Missas que se celebram só com crianças, isto é, as que ainda não entraram na adolescência, ou àquelas Missas nas quais a maior parte dos participantes é criança.\nO prefácio dessa Oração Eucarística, por sua estrutura e índole peculiar, não pode ser substituído por outros prefácios.",
            "",
            "CP: O Senhor esteja convosco.",
            "AS: Ele está no meio de nós.",
            "CP: Corações ao alto.",
            "AS: O nosso coração está em Deus.",
            "CP: Demos graças ao Senhor, nosso Deus.",
            "AS: É nosso dever e nossa salvação.",
            "Deus, nosso Pai, nós vos agradecemos, porque nos criastes, a fim de vivermos para vós, amando-nos como irmãos.",
            "Por vosso dom, podemos viver como amigos e repartir uns com os outros as coisas bonitas que temos e as dificuldades que passamos.",
            "Porque sois o Deus dos vivos, nos chamastes à vida e quereis que sejamos felizes para sempre. Jesus é o primeiro que vós ressuscitastes dentre os mortos e lhe destes a vida nova. Também a nós prometestes vida sem fim, sem miséria e sem dor.",
            "Por isso, ó Pai, felizes e agradecidos, em comunhão com todos os que acreditam em vós, com os Santos e os Anjos, exultantes, cantamos (dizemos) a uma só voz:",
            "AS: Santo, Santo, Santo, Senhor Deus do universo! O céu e a terra proclamam a vossa glória. Hosana nas alturas! Bendito o que vem em nome do Senhor! Hosana nas alturas!",
            "CP: Na verdade, ó Pai, vós sois santo, sois muito bom para nós e amais todas as pessoas do mundo. Agradecemos, em primeiro lugar, pelo vosso Filho, Jesus Cristo. Ele veio ao mundo porque as pessoas se afastaram de vós pelo pecado e não conseguiam mais se entender. Ele abriu nossos olhos e ouvidos para vos conhecer como Pai e nos amarmos como irmãos e irmãs.",
            "AS: Glória a vós, ó Pai, que em Cristo nos salvais.",
            "Ele nos anunciou a vida plena da ressurreição que viveremos para sempre junto de vós. Ele percorreu, antes de nós, o caminho do amor para que seguíssemos seus passos. Jesus agora nos reúne ao redor deste altar para fazermos o que na última Ceia ele mesmo fez com seus discípulos.",
            "AS: Glória a vós, ó Pai, que em Cristo nos salvais.",
            "CC: Ó Pai, vós que sois tão bom, mandai vosso Espírito Santo para santificar estes dons do pão e do vinho. Eles serão para nós o Corpo ✠ e o Sangue de Jesus Cristo, vosso Filho.",
            "AS: Enviai o vosso Espírito Santo.",
            "Na noite antes de morrer por nós, Jesus pôs-se à mesa com seus apóstolos, tomou o pão em suas mãos, e, rezando, deu graças; partiu o pão e o deu a seus amigos, dizendo:",
            "TOMAI, TODOS, E COMEI: ISTO É O MEU CORPO, QUE SERÁ ENTREGUE POR VÓS.",
            "Do mesmo modo, no fim da Ceia, Jesus tomou em suas mãos o cálice com vinho, rezou em ação de graças e o deu a seus amigos, dizendo:",
            "TOMAI, TODOS, E BEBEI: ESTE É O CÁLICE DO MEU SANGUE, O SANGUE DA NOVA E ETERNA ALIANÇA, QUE SERÁ DERRAMADO POR VÓS E POR TODOS PARA REMISSÃO DOS PECADOS. FAZEI ISTO EM MEMÓRIA DE MIM.",
            "Mistério da fé!",
            "AS: Anunciamos, Senhor, a vossa morte e proclamamos a vossa ressurreição. Vinde, Senhor Jesus!",
            "Por isso, Pai santo, aqui estamos diante de vós, e, com alegria, celebramos a memória do que Jesus Cristo fez para nossa salvação. Neste santo sacrifício, que ele confiou à sua Igreja, celebramos sua morte e ressurreição. Pai santo, que estais nos céus, aceitai-nos com vosso Filho amado. Ele sofreu livremente a morte por nós; vós, porém, o ressuscitastes.",
            "AS: Com Jesus, recebei a nossa vida!",
            "Ó Pai, Jesus agora vive sempre junto de vós, mas ao mesmo tempo está aqui conosco. Um dia, ele virá em sua glória e o seu reino não terá fim. Então, ninguém mais vai sofrer, ninguém mais vai chorar, ninguém mais vai ficar triste: o pecado e a morte não mais dominarão.",
            "AS: Glória a vós, ó Pai, que em Cristo nos salvais.",
            "Pai santo, vós nos chamastes para recebermos nesta mesa, com alegria, o Corpo de Cristo. Fortificados por este alimento, possamos agradar-vos sempre mais e pela comunhão do Espírito Santo nos tornemos um só corpo no amor.",
            "AS: Fazei de nós um só corpo e um só espírito!",
            {
                contexto: "memento dos vivos",
                texto: [
                    "1C: Lembrai-vos, ó Pai, do nosso Papa N., do nosso Bispo N. e dos outros bispos. Ajudai os discípulos de Cristo, para que vivam em paz e repartam com todos o dom da alegria."
                ],
                variacoes: [
                    {
                        contexto: "no tempo pascal",
                        texto: [
                            "1C: Lembrai-vos, ó Pai, do nosso Papa N., do nosso Bispo N. e dos outros bispos. Fazei que os corações dos vossos fiéis sejam repletos com as alegrias da Páscoa e levem estas mesmas alegrias aos que vivem na tristeza."
                        ]
                    }
                ]
            },
            "Concedei que, um dia, estejamos junto a vós, morando para sempre em vossa casa com Jesus e Maria, sua Mãe, São N. e todos os Santos, e com nossos irmãos falecidos.",
            "CP ou CC: Por Cristo, com Cristo, e em Cristo, a vós, Deus Pai todo-poderoso, na unidade do Espírito Santo, toda honra e toda glória, por todos os séculos dos séculos.",
            "AS: Amém.",
            "E segue o Rito da Comunhão…"
        ]
    }
];
